# Generated by Django 6.0.6 on 2026-07-18 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Membre Free'), ('premium', 'Membre Premium')], default='free', max_length=10)),
                ('completed_contents', models.PositiveIntegerField(default=0)),
                ('training_hours', models.PositiveIntegerField(default=0)),
                ('events_attended', models.PositiveIntegerField(default=0)),
                ('community_points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
