# Generated by Django 6.0.6 on 2026-07-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('spotlight', 'CEO & Leaders Spotlight'), ('strategic', 'Strategic Talk'), ('decoding', 'Market & Strategy Decoding'), ('learning', 'AFI Learning')], default='strategic', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
