# Generated by Django 6.0.6 on 2026-07-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Réserver'), ('registered', 'Inscrit'), ('early_bird', 'Early Bird')], default='open', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
