# Generated by Django 6.0.7 on 2026-09-11 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=255, unique=True)),
                ('sus_Start_time', models.DateTimeField(auto_now_add=True)),
                ('sus_End_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-sus_Start_time'],
                'constraints': [models.UniqueConstraint(fields=('user_uuid',), name='unique_user_uuid')],
            },
        ),
        migrations.CreateModel(
            name='ReservationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('is_counted', models.BooleanField(default=False)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_entry', to='content.reservation')),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
    ]
