"""
Django settings for fin project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = config('SECRET_KEY', default='dev-secret-key')

DEBUG = config('DEBUG', default=True, cast=bool)


ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1'
    'afritech-bsa6.onrender.com',
] 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'content',
    'accounts',
    'stats',
    'drf_spectacular',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'web',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default='')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = '/assets/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'web' / 'assets',
]



CORS_ALLOWED_ORIGINS = [
    'http://localhost:5500',
    'http://127.0.0.1:5500',
    'http://localhost:8000',
    'https://afritech-front.onrender.com',
]

CRSF_TRUSTED_ORIGINS = [
    'https://afritech-front.onrender.com',
]

# YouTube
YOUTUBE_API_KEY = config('YOUTUBE_API_KEY')
YOUTUBE_CHANNEL_ID = config('YOUTUBE_CHANNEL_ID')  # celui de "Africa Fintech Inside"


# Email
# Par défaut : backend console (les emails s'affichent dans le terminal en dev).
# En prod, définir EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# et renseigner les variables SMTP dans le .env.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='Africa Fintech Inside <no-reply@africafintechinside.com>',
)


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}


# À ajouter dans fin/settings.py :

# 1) Ajouter 'django_crontab' à INSTALLED_APPS (nécessite : pip install django-crontab)
#    INSTALLED_APPS = [
#        ...
#        'django_crontab',
#    ]

# 2) Ajouter ce bloc, par exemple juste après le bloc YouTube existant :

from .cron_utils import minutes_to_cron  # noqa: E402

# Une seule variable pilote l'intervalle, en dev (Windows) comme en prod (Linux).
SYNC_INTERVAL_MINUTES = config('SYNC_INTERVAL_MINUTES', default=60, cast=int)
_SYNC_SCHEDULE = minutes_to_cron(SYNC_INTERVAL_MINUTES)

# django-crontab (actif uniquement en prod / Linux — voir plus bas pourquoi).
CRONJOBS = [
    (_SYNC_SCHEDULE, 'django.core.management.call_command', ['sync_youtube']),
    (_SYNC_SCHEDULE, 'django.core.management.call_command', ['sync_stats']),
]


REST_FRAMEWORK = {
    
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Lecture publique par défaut ; les vues protégées le déclarent explicitement.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Mon API',
    'DESCRIPTION': 'Documentation de mon API',
    'VERSION': '1.0.0',
}

MIXPANEL_PROJECT_ID = config('MIXPANEL_PROJECT_ID')
MIXPANEL_SERVICE_ACCOUNT_USERNAME = config('MIXPANEL_SERVICE_ACCOUNT_USERNAME')
MIXPANEL_SERVICE_ACCOUNT_SECRET = config('MIXPANEL_SERVICE_ACCOUNT_SECRET')